let num1 = Math.floor(Math.random() * 900) + 100;
let num2 = Math.floor(Math.random() * 900) + 100;
let num3 = Math.floor(Math.random() * 900) + 100;
let num4 = Math.floor(Math.random() * 900) + 100;
let num5 = Math.floor(Math.random() * 900) + 100;
let max = num1;
if (max < num2) max = num2;
if (max < num3) max = num3;
if (max < num4) max = num4;
if (max < num5) max = num5;
let min = num1;
if (min > num2) min = num2;
if (min > num3) min = num3;
if (min > num4) min = num4;
if (min > num5) min = num5;
console.log("Maximux : " + max);
console.log("Minimum : " + min);
